spring:
  application:
    name: enterprise-ai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EnterpriseAi
    username: root
    password: ${MYSQL_PASSWORD}
